name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101' # SDK Version
      - name: Build
        run: dotnet build --configuration Release src/ModernCaching
      - name: Test
        run: dotnet test src/
